name: Java CloudSim CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Compile Java files with CloudSim JARs
      run: javac -cp "./cloudsim-3.0.3.jar:./commons-math3-3.6.1.jar" -d . *.java

    - name: Run CloudSim Simulation
      run: java -cp ".:cloudsim-3.0.3.jar:commons-math3-3.6.1.jar" Main
