name: Java CloudSim CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'adoptopenjdk'
        java-version: '8'

    - name: Compile Java files with CloudSim JARs
      run: |
        mkdir -p out
        javac -cp ".:cloudsim-3.0.3.jar:commons-math3-3.6.1.jar" -d out $(find . -name "*.java")

    - name: Run Main class
      run: |
        java -cp "out:cloudsim-3.0.3.jar:commons-math3-3.6.1.jar" Main
