name: Java CloudSim CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Correct OpenJDK distribution

    - name: Verify Java installation
      run: java -version

    - name: Set classpath and compile Java files
      run: |
        export CLASSPATH=$(pwd)/cloudsim-3.0.3.jar:$(pwd)/commons-math3-3.6.1.jar
        echo "Classpath is $CLASSPATH"
        javac -cp "$CLASSPATH" -d . $(find . -name "*.java")

    - name: Run CloudSim Simulation
      run: |
        export CLASSPATH=$(pwd)/cloudsim-3.0.3.jar:$(pwd)/commons-math3-3.6.1.jar
        java -cp "$CLASSPATH:." Main
