name: Java CloudSim CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Use the JDK version you need (e.g., 11, 17, etc.)
        distribution: 'adoptium'  # Correct distribution name for OpenJDK

    - name: Check Java Version
      run: java -version  # This will print the installed Java version

    - name: Add JARs to classpath
      run: echo $JAVA_HOME

    - name: Compile Java files with CloudSim JARs
      run: javac -cp "cloudsim-3.0.3.jar:commons-math3-3.6.1.jar" -d . *.java

    - name: Run CloudSim Simulation
      run: java -cp ".:cloudsim-3.0.3.jar:commons-math3-3.6.1.jar" Main

